# Generated by Django 5.1.3 on 2025-04-13 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('PostalCode', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=20)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('IdentificationNumber', models.CharField(max_length=50)),
                ('RegistrationDate', models.DateField()),
                ('Status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('blocked', 'Blocked')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardAccount',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('CardNumber', models.CharField(max_length=20)),
                ('CardType', models.CharField(max_length=20)),
                ('CreditLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CurrentBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AvailableCredit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ExpiryDate', models.DateField()),
                ('IssueDate', models.DateField()),
                ('PaymentDueDate', models.DateField()),
                ('MinimumPaymentPercentage', models.CharField(max_length=50)),
                ('InterestRate', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('blocked', 'Blocked')], default='active', max_length=10)),
                ('PreviousBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('TotalPayment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('NewPurchases', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('MinDue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('TotalDue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('CashLimit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('AvailableCash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RewardPoint',
            fields=[
                ('RewardID', models.AutoField(primary_key=True, serialize=False)),
                ('PointsEarned', models.IntegerField(default=0)),
                ('PointsRedeemed', models.IntegerField(default=0)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.creditcardaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateField()),
                ('MerchantName', models.CharField(max_length=100)),
                ('MerchantLocation', models.CharField(max_length=100)),
                ('MerchantCategory', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TransactionType', models.CharField(max_length=20)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.creditcardaccount')),
            ],
        ),
    ]
